// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gates.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGates = `-- name: CountGates :one
SELECT count(*) FROM gates
`

func (q *Queries) CountGates(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGates)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGate = `-- name: CreateGate :one
INSERT INTO gates (name, gate_token_hash, status_ttl_seconds)
VALUES ($1, $2, $3)
RETURNING id, name, gate_token_hash, status_ttl_seconds, created_at, updated_at
`

type CreateGateParams struct {
	Name             string `json:"name"`
	GateTokenHash    string `json:"gate_token_hash"`
	StatusTtlSeconds int32  `json:"status_ttl_seconds"`
}

func (q *Queries) CreateGate(ctx context.Context, arg CreateGateParams) (Gate, error) {
	row := q.db.QueryRow(ctx, createGate, arg.Name, arg.GateTokenHash, arg.StatusTtlSeconds)
	var i Gate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GateTokenHash,
		&i.StatusTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGate = `-- name: DeleteGate :exec
DELETE FROM gates WHERE id = $1
`

func (q *Queries) DeleteGate(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGate, id)
	return err
}

const getGateByID = `-- name: GetGateByID :one
SELECT id, name, gate_token_hash, status_ttl_seconds, created_at, updated_at FROM gates
WHERE id = $1
`

func (q *Queries) GetGateByID(ctx context.Context, id pgtype.UUID) (Gate, error) {
	row := q.db.QueryRow(ctx, getGateByID, id)
	var i Gate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GateTokenHash,
		&i.StatusTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGates = `-- name: ListGates :many
SELECT id, name, gate_token_hash, status_ttl_seconds, created_at, updated_at FROM gates
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListGatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListGates(ctx context.Context, arg ListGatesParams) ([]Gate, error) {
	rows, err := q.db.Query(ctx, listGates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Gate{}
	for rows.Next() {
		var i Gate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GateTokenHash,
			&i.StatusTtlSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGate = `-- name: UpdateGate :one
UPDATE gates
SET name = $2, status_ttl_seconds = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, gate_token_hash, status_ttl_seconds, created_at, updated_at
`

type UpdateGateParams struct {
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	StatusTtlSeconds int32       `json:"status_ttl_seconds"`
}

func (q *Queries) UpdateGate(ctx context.Context, arg UpdateGateParams) (Gate, error) {
	row := q.db.QueryRow(ctx, updateGate, arg.ID, arg.Name, arg.StatusTtlSeconds)
	var i Gate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GateTokenHash,
		&i.StatusTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGateToken = `-- name: UpdateGateToken :one
UPDATE gates
SET gate_token_hash = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, gate_token_hash, status_ttl_seconds, created_at, updated_at
`

type UpdateGateTokenParams struct {
	ID            pgtype.UUID `json:"id"`
	GateTokenHash string      `json:"gate_token_hash"`
}

func (q *Queries) UpdateGateToken(ctx context.Context, arg UpdateGateTokenParams) (Gate, error) {
	row := q.db.QueryRow(ctx, updateGateToken, arg.ID, arg.GateTokenHash)
	var i Gate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GateTokenHash,
		&i.StatusTtlSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
