// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gate_actions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGateAction = `-- name: CreateGateAction :one
INSERT INTO gate_actions (gate_id, action_type, transport_type, config)
VALUES ($1, $2, $3, $4)
RETURNING id, gate_id, action_type, transport_type, config
`

type CreateGateActionParams struct {
	GateID        pgtype.UUID `json:"gate_id"`
	ActionType    string      `json:"action_type"`
	TransportType string      `json:"transport_type"`
	Config        []byte      `json:"config"`
}

func (q *Queries) CreateGateAction(ctx context.Context, arg CreateGateActionParams) (GateAction, error) {
	row := q.db.QueryRow(ctx, createGateAction,
		arg.GateID,
		arg.ActionType,
		arg.TransportType,
		arg.Config,
	)
	var i GateAction
	err := row.Scan(
		&i.ID,
		&i.GateID,
		&i.ActionType,
		&i.TransportType,
		&i.Config,
	)
	return i, err
}

const deleteGateAction = `-- name: DeleteGateAction :exec
DELETE FROM gate_actions
WHERE gate_id = $1 AND action_type = $2
`

type DeleteGateActionParams struct {
	GateID     pgtype.UUID `json:"gate_id"`
	ActionType string      `json:"action_type"`
}

func (q *Queries) DeleteGateAction(ctx context.Context, arg DeleteGateActionParams) error {
	_, err := q.db.Exec(ctx, deleteGateAction, arg.GateID, arg.ActionType)
	return err
}

const getGateAction = `-- name: GetGateAction :one
SELECT id, gate_id, action_type, transport_type, config FROM gate_actions
WHERE gate_id = $1 AND action_type = $2
`

type GetGateActionParams struct {
	GateID     pgtype.UUID `json:"gate_id"`
	ActionType string      `json:"action_type"`
}

func (q *Queries) GetGateAction(ctx context.Context, arg GetGateActionParams) (GateAction, error) {
	row := q.db.QueryRow(ctx, getGateAction, arg.GateID, arg.ActionType)
	var i GateAction
	err := row.Scan(
		&i.ID,
		&i.GateID,
		&i.ActionType,
		&i.TransportType,
		&i.Config,
	)
	return i, err
}

const listGateActionsByGate = `-- name: ListGateActionsByGate :many
SELECT id, gate_id, action_type, transport_type, config FROM gate_actions
WHERE gate_id = $1
`

func (q *Queries) ListGateActionsByGate(ctx context.Context, gateID pgtype.UUID) ([]GateAction, error) {
	rows, err := q.db.Query(ctx, listGateActionsByGate, gateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GateAction{}
	for rows.Next() {
		var i GateAction
		if err := rows.Scan(
			&i.ID,
			&i.GateID,
			&i.ActionType,
			&i.TransportType,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGateAction = `-- name: UpdateGateAction :one
UPDATE gate_actions
SET transport_type = $3, config = $4
WHERE gate_id = $1 AND action_type = $2
RETURNING id, gate_id, action_type, transport_type, config
`

type UpdateGateActionParams struct {
	GateID        pgtype.UUID `json:"gate_id"`
	ActionType    string      `json:"action_type"`
	TransportType string      `json:"transport_type"`
	Config        []byte      `json:"config"`
}

func (q *Queries) UpdateGateAction(ctx context.Context, arg UpdateGateActionParams) (GateAction, error) {
	row := q.db.QueryRow(ctx, updateGateAction,
		arg.GateID,
		arg.ActionType,
		arg.TransportType,
		arg.Config,
	)
	var i GateAction
	err := row.Scan(
		&i.ID,
		&i.GateID,
		&i.ActionType,
		&i.TransportType,
		&i.Config,
	)
	return i, err
}
