// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members
`

func (q *Queries) CountMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (username, display_name, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, display_name, password_hash, role, created_at, updated_at
`

type CreateMemberParams struct {
	Username     string      `json:"username"`
	DisplayName  pgtype.Text `json:"display_name"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, username, display_name, password_hash, role, created_at, updated_at FROM members
WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemberByUsername = `-- name: GetMemberByUsername :one
SELECT id, username, display_name, password_hash, role, created_at, updated_at FROM members
WHERE username = $1
`

func (q *Queries) GetMemberByUsername(ctx context.Context, username string) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUsername, username)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, username, display_name, password_hash, role, created_at, updated_at FROM members
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListMembersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Member{}
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members
SET username = $2, display_name = $3, role = $4, updated_at = now()
WHERE id = $1
RETURNING id, username, display_name, password_hash, role, created_at, updated_at
`

type UpdateMemberParams struct {
	ID          pgtype.UUID `json:"id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	Role        string      `json:"role"`
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
