// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package repository

import "context"

const countMembersByRole = `-- name: CountMembersByRole :one
SELECT count(*) FROM members WHERE role = $1`

func (q *Queries) CountMembersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}
