// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (member_id, gate_id, can_open, can_close, can_view_status, can_manage)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, member_id, gate_id, can_open, can_close, can_view_status, can_manage
`

type CreatePermissionParams struct {
	MemberID      pgtype.UUID `json:"member_id"`
	GateID        pgtype.UUID `json:"gate_id"`
	CanOpen       bool        `json:"can_open"`
	CanClose      bool        `json:"can_close"`
	CanViewStatus bool        `json:"can_view_status"`
	CanManage     bool        `json:"can_manage"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.MemberID,
		arg.GateID,
		arg.CanOpen,
		arg.CanClose,
		arg.CanViewStatus,
		arg.CanManage,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GateID,
		&i.CanOpen,
		&i.CanClose,
		&i.CanViewStatus,
		&i.CanManage,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE member_id = $1 AND gate_id = $2
`

type DeletePermissionParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	GateID   pgtype.UUID `json:"gate_id"`
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.Exec(ctx, deletePermission, arg.MemberID, arg.GateID)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT id, member_id, gate_id, can_open, can_close, can_view_status, can_manage FROM permissions
WHERE member_id = $1 AND gate_id = $2
`

type GetPermissionParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	GateID   pgtype.UUID `json:"gate_id"`
}

func (q *Queries) GetPermission(ctx context.Context, arg GetPermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, arg.MemberID, arg.GateID)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GateID,
		&i.CanOpen,
		&i.CanClose,
		&i.CanViewStatus,
		&i.CanManage,
	)
	return i, err
}

const listPermissionsByGate = `-- name: ListPermissionsByGate :many
SELECT id, member_id, gate_id, can_open, can_close, can_view_status, can_manage FROM permissions
WHERE gate_id = $1
`

func (q *Queries) ListPermissionsByGate(ctx context.Context, gateID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByGate, gateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.GateID,
			&i.CanOpen,
			&i.CanClose,
			&i.CanViewStatus,
			&i.CanManage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByMember = `-- name: ListPermissionsByMember :many
SELECT id, member_id, gate_id, can_open, can_close, can_view_status, can_manage FROM permissions
WHERE member_id = $1
`

func (q *Queries) ListPermissionsByMember(ctx context.Context, memberID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.GateID,
			&i.CanOpen,
			&i.CanClose,
			&i.CanViewStatus,
			&i.CanManage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE permissions
SET can_open = $3, can_close = $4, can_view_status = $5, can_manage = $6
WHERE member_id = $1 AND gate_id = $2
RETURNING id, member_id, gate_id, can_open, can_close, can_view_status, can_manage
`

type UpdatePermissionParams struct {
	MemberID      pgtype.UUID `json:"member_id"`
	GateID        pgtype.UUID `json:"gate_id"`
	CanOpen       bool        `json:"can_open"`
	CanClose      bool        `json:"can_close"`
	CanViewStatus bool        `json:"can_view_status"`
	CanManage     bool        `json:"can_manage"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.MemberID,
		arg.GateID,
		arg.CanOpen,
		arg.CanClose,
		arg.CanViewStatus,
		arg.CanManage,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.GateID,
		&i.CanOpen,
		&i.CanClose,
		&i.CanViewStatus,
		&i.CanManage,
	)
	return i, err
}
