// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedules.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachScheduleToMemberGate = `-- name: AttachScheduleToMemberGate :exec
INSERT INTO member_gate_schedules (member_id, gate_id, schedule_id)
VALUES ($1, $2, $3)
`

type AttachScheduleToMemberGateParams struct {
	MemberID   pgtype.UUID `json:"member_id"`
	GateID     pgtype.UUID `json:"gate_id"`
	ScheduleID pgtype.UUID `json:"schedule_id"`
}

func (q *Queries) AttachScheduleToMemberGate(ctx context.Context, arg AttachScheduleToMemberGateParams) error {
	_, err := q.db.Exec(ctx, attachScheduleToMemberGate, arg.MemberID, arg.GateID, arg.ScheduleID)
	return err
}

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (name, scope, owner_id, expression)
VALUES ($1, $2, $3, $4)
RETURNING id, name, scope, owner_id, expression, created_at, updated_at
`

type CreateScheduleParams struct {
	Name       string      `json:"name"`
	Scope      string      `json:"scope"`
	OwnerID    pgtype.UUID `json:"owner_id"`
	Expression []byte      `json:"expression"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.Name,
		arg.Scope,
		arg.OwnerID,
		arg.Expression,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.OwnerID,
		&i.Expression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const detachScheduleFromMemberGate = `-- name: DetachScheduleFromMemberGate :exec
DELETE FROM member_gate_schedules
WHERE member_id = $1 AND gate_id = $2 AND schedule_id = $3
`

type DetachScheduleFromMemberGateParams struct {
	MemberID   pgtype.UUID `json:"member_id"`
	GateID     pgtype.UUID `json:"gate_id"`
	ScheduleID pgtype.UUID `json:"schedule_id"`
}

func (q *Queries) DetachScheduleFromMemberGate(ctx context.Context, arg DetachScheduleFromMemberGateParams) error {
	_, err := q.db.Exec(ctx, detachScheduleFromMemberGate, arg.MemberID, arg.GateID, arg.ScheduleID)
	return err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, name, scope, owner_id, expression, created_at, updated_at FROM schedules
WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id pgtype.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.OwnerID,
		&i.Expression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdminSchedules = `-- name: ListAdminSchedules :many
SELECT id, name, scope, owner_id, expression, created_at, updated_at FROM schedules
WHERE scope = 'ADMIN'
ORDER BY created_at ASC
LIMIT $1 OFFSET $2
`

type ListAdminSchedulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdminSchedules(ctx context.Context, arg ListAdminSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listAdminSchedules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.OwnerID,
			&i.Expression,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalSchedules = `-- name: ListPersonalSchedules :many
SELECT id, name, scope, owner_id, expression, created_at, updated_at FROM schedules
WHERE scope = 'PERSONAL' AND owner_id = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListPersonalSchedulesParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListPersonalSchedules(ctx context.Context, arg ListPersonalSchedulesParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listPersonalSchedules, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.OwnerID,
			&i.Expression,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesForMemberGate = `-- name: ListSchedulesForMemberGate :many
SELECT s.id, s.name, s.scope, s.owner_id, s.expression, s.created_at, s.updated_at FROM schedules s
JOIN member_gate_schedules mgs ON mgs.schedule_id = s.id
WHERE mgs.member_id = $1 AND mgs.gate_id = $2
`

type ListSchedulesForMemberGateParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	GateID   pgtype.UUID `json:"gate_id"`
}

func (q *Queries) ListSchedulesForMemberGate(ctx context.Context, arg ListSchedulesForMemberGateParams) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesForMemberGate, arg.MemberID, arg.GateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Schedule{}
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Scope,
			&i.OwnerID,
			&i.Expression,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET name = $2, expression = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, scope, owner_id, expression, created_at, updated_at
`

type UpdateScheduleParams struct {
	ID         pgtype.UUID `json:"id"`
	Name       string      `json:"name"`
	Expression []byte      `json:"expression"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule, arg.ID, arg.Name, arg.Expression)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Scope,
		&i.OwnerID,
		&i.Expression,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
